
# Setup
title:            Tim Roller CFA
tagline:          'Home'
description:      'EX NIHILO NIHIL FIT'
url:              
baseurl:          /


author:
  name:           'Tim Roller'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/TimRoller/
